export const cvProfileFacts = [
  "Mohamed Ezer Bouzouraa is a software and AI engineer based in Tunis, Tunisia.",
  "He is a motivated, self-taught engineer specializing in artificial intelligence and machine learning.",
  "He is currently studying Engineering with a Software & AI specialization at INSAT (National Institute of Applied Sciences and Technology), 2024 to present.",
  "He completed his Baccalaureate (Tunisian curriculum) at Lycée Salah Ben Youssef in 2024 with a score of 18.28/20.",
  "Contact email: mrezeryt178@gmail.com.",
  "LinkedIn: linkedin.com/in/mohamed-ezer-bouzouraa. GitHub: github.com/mohamedezerbouzouraa.",
  "Programming skills: Python, JavaScript, C/C++, Java, PHP, SQL.",
  "AI/ML stack: TensorFlow, PyTorch, scikit-learn, Deep Learning, LLMs, RAG.",
  "Data science tools: NumPy, Pandas, Matplotlib, MediaPipe, YOLOv8.",
  "Engineering and tools: Flask, Symfony, Git, Linux, REST APIs.",
  "Featured project: INSAT RAG Assistant, a multilingual chatbot for INSAT built with LangChain, BM25 retrieval, Groq LLMs, and Flask.",
  "Featured project: RLHF World Cup 2026, a FIFA World Cup chatbot using Llama 3.3 70B via Groq with a reinforcement-learning-from-human-feedback loop.",
  "Featured project: Reviewify, an LLM-powered multi-tool agent that turns bullet points into polished employee reviews for HR managers.",
  "Featured project: Student Advisor AI, an interactive chatbot that guides students step by step and assigns exercises.",
  "Featured project: MatchPicker AI Dashboard, a football analytics dashboard with real-time match analysis and a custom AI chatbot.",
  "Featured project: YOLOv8 Car Counter, a lightweight vehicle detection and counting tool using Ultralytics YOLOv8.",
  "Featured project: Push-Up Counter, which counts push-up repetitions using MediaPipe pose estimation and an Adaline model.",
  "Featured project: Soccer Team Detection, which detects players and classifies them by team using YOLOv8 and jersey color analysis.",
  "Featured project: Lifestyle Stability Index, an SVM classifier tuned with GridSearchCV that labels routines as stable or unstable.",
  "Featured project: Geo Country Guesser, a Decision Tree based game that guesses a country from geographic and demographic features.",
  "Featured project: SpamGuard, a desktop spam detector using TF-IDF and an SVM with the kernel trick.",
  "Featured project: Vehicle Health Predictor, a Logistic Regression pipeline that classifies vehicles as healthy or unhealthy from sensor data.",
  "Featured project: Mathematicians Legacy, a full-stack platform with an interactive map of mathematicians built with Symfony and a Gemini-powered chatbot.",
  "Featured project: JobApplication Tracker AI, an AI-powered job application tracker built with the Model Context Protocol (MCP), Pydantic, and prompt_toolkit.",
  "He writes a Maths Blog about proofs, number theory, and logic, and an article on the history of prime numbers.",
  "Spoken languages: Arabic (native), French (fluent), English (high level), Italian (intermediate).",
  "He is open to internship and collaboration opportunities in AI and software engineering fields.",
];

export const cvProfileFactsFr = [
  "Mohamed Ezer Bouzouraa est ingénieur logiciel et IA basé à Tunis, en Tunisie.",
  "C'est un ingénieur autodidacte et motivé, spécialisé en intelligence artificielle et apprentissage automatique.",
  "Il étudie actuellement l'ingénierie avec une spécialisation Logiciel & IA à l'INSAT (Institut National des Sciences Appliquées et de Technologie), depuis 2024.",
  "Il a obtenu son Baccalauréat (système tunisien) au Lycée Salah Ben Youssef en 2024 avec une moyenne de 18.28/20.",
  "Email de contact : mrezeryt178@gmail.com.",
  "LinkedIn : linkedin.com/in/mohamed-ezer-bouzouraa. GitHub : github.com/mohamedezerbouzouraa.",
  "Compétences en programmation : Python, JavaScript, C/C++, Java, PHP, SQL.",
  "Stack IA/ML : TensorFlow, PyTorch, scikit-learn, Deep Learning, LLMs, RAG.",
  "Outils de data science : NumPy, Pandas, Matplotlib, MediaPipe, YOLOv8.",
  "Ingénierie et outils : Flask, Symfony, Git, Linux, REST APIs.",
  "Projet phare : INSAT RAG Assistant, un chatbot multilingue pour l'INSAT construit avec LangChain, la récupération BM25, des LLMs Groq et Flask.",
  "Projet phare : RLHF World Cup 2026, un chatbot sur la Coupe du Monde utilisant Llama 3.3 70B via Groq avec une boucle de RLHF.",
  "Projet phare : Reviewify, un agent LLM multi-outils qui transforme des points clés en évaluations de performance pour les RH.",
  "Projet phare : Student Advisor AI, un chatbot interactif qui guide les étudiants étape par étape et propose des exercices.",
  "Projet phare : MatchPicker AI Dashboard, un tableau de bord d'analyse football en temps réel avec un chatbot IA sur mesure.",
  "Projet phare : YOLOv8 Car Counter, un outil léger de détection et comptage de véhicules avec YOLOv8.",
  "Projet phare : Push-Up Counter, qui compte les répétitions de pompes via MediaPipe et un modèle Adaline.",
  "Projet phare : Soccer Team Detection, qui détecte les joueurs et les classe par équipe via YOLOv8 et la couleur du maillot.",
  "Projet phare : Lifestyle Stability Index, un classificateur SVM optimisé avec GridSearchCV pour des routines stables ou instables.",
  "Projet phare : Geo Country Guesser, un jeu basé sur un arbre de décision qui devine un pays à partir de caractéristiques géographiques.",
  "Projet phare : SpamGuard, un détecteur de spam de bureau utilisant TF-IDF et un SVM à noyau.",
  "Projet phare : Vehicle Health Predictor, un pipeline de régression logistique qui classe les véhicules sains ou défaillants.",
  "Projet phare : Mathematicians Legacy, une plateforme full-stack avec une carte interactive des mathématiciens et un chatbot Gemini.",
  "Projet phare : JobApplication Tracker AI, un suivi de candidatures basé sur le Model Context Protocol (MCP), Pydantic et prompt_toolkit.",
  "Il tient un Maths Blog sur les preuves, la théorie des nombres et la logique, ainsi qu'un article sur l'histoire des nombres premiers.",
  "Langues parlées : arabe (natif), français (courant), anglais (niveau avancé), italien (intermédiaire).",
  "Il est ouvert aux opportunités de stage et de collaboration en IA et en génie logiciel.",
];
